name: Docker Image CI

on:
  push:
#     branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build Image and Push to Docker Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER }}/${{ secrets.DOCKER_IMAGE }}:latest
      -  
        name: Connect to Server via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SECRET_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo docker container stop ${{ secrets.DOCKER_CONTAINER }}
            sudo docker container rm ${{ secrets.DOCKER_CONTAINER }}
            sudo docker image rm ${{ secrets.DOCKER_HUB_USER }}/${{ secrets.DOCKER_IMAGE }}:latest
            sudo docker run --name ${{ secrets.DOCKER_CONTAINER }} -p 8008:8008 -d -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=3306 -e DB_USER=${{ secrets.DB_USER }} -e DB_PASS=${{ secrets.DB_PASS }} -e DB_NAME=${{ secrets.DB_NAME }} -e JWT_ACCESS_KEY=${{ secrets.JWT_ACCESS_KEY }} -e JWT_REFRESH_KEY=${{ secrets.JWT_REFRESH_KEY }} -e CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} -e CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} -e CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} ${{ secrets.DOCKER_HUB_USER }}/${{ secrets.DOCKER_IMAGE }}:latest
